# gates.pyi
# This file is for IntelliSense only. No logic allowed!

def nand(a: bool, b: bool) -> bool: ...
def nor(a: bool, b: bool) -> bool: ...
def xor(a: bool, b: bool) -> bool: ...
def xnor(a: bool, b: bool) -> bool: ...

class logicInt:
    def nand(self, a: int, b: int) -> int: ...
    def nor(self, a: int, b: int) -> int: ...
    def xor(self, a: int, b: int) -> int: ...
    def xnor(self, a: int, b: int) -> int: ...